name: enspred
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.11
  - numpy
  - xarray
  - matplotlib
  - seaborn
  - cartopy
  - xesmf>0.8
  - jupyter
  - black
  - black-jupyter
  - intake-esm
  - dask
  - regionmask
  - scikit-learn
  - tqdm
  - pip:
    - git+https://github.com/LinkedEarth/pylipd.git@main
